// <auto-generated />
using System;
using FullstackRessourcix;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FullstackRessourcix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FullstackRessourcix.AbsenceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<bool>("Overlap")
                        .HasColumnType("boolean");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Until")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("requests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e978e11-0a00-4e05-b61a-007763f529cd"),
                            Days = 10,
                            EmployeeId = new Guid("4c3469de-428f-437e-b752-46f56714f063"),
                            From = new DateOnly(2026, 7, 13),
                            Overlap = true,
                            Status = 0,
                            SubmittedOn = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0,
                            Until = new DateOnly(2026, 7, 24)
                        });
                });

            modelBuilder.Entity("FullstackRessourcix.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Reference")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("FullstackRessourcix.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("VacationDays")
                        .HasColumnType("double precision");

                    b.Property<int>("Workload")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c3469de-428f-437e-b752-46f56714f063"),
                            IsActive = true,
                            MustChangePassword = true,
                            Name = "Morris Meier",
                            PasswordHash = "AQAAAAIAAYagAAAAEB9r8iV+OfZIu2V5H1x/Hh3SM3oPW8VHpRdMSxKV+bTtHl2pQleQPQzWZRZstzlw2w==",
                            PermissionLevel = 1,
                            Role = "Mitarbeiter",
                            Username = "morris.meier",
                            VacationDays = 25.0,
                            Workload = 100
                        },
                        new
                        {
                            Id = new Guid("86df2463-1bcd-42de-bb97-2cf112caeabf"),
                            IsActive = true,
                            MustChangePassword = true,
                            Name = "Pedro Santos",
                            PasswordHash = "AQAAAAIAAYagAAAAEB9r8iV+OfZIu2V5H1x/Hh3SM3oPW8VHpRdMSxKV+bTtHl2pQleQPQzWZRZstzlw2w==",
                            PermissionLevel = 5,
                            Role = "Planer/Leitung",
                            Username = "pedro.santos",
                            VacationDays = 25.0,
                            Workload = 100
                        },
                        new
                        {
                            Id = new Guid("77f37330-cb2b-4a5b-9f6a-6c2d19fde288"),
                            IsActive = true,
                            MustChangePassword = true,
                            Name = "Lena Brunner",
                            PasswordHash = "AQAAAAIAAYagAAAAEB9r8iV+OfZIu2V5H1x/Hh3SM3oPW8VHpRdMSxKV+bTtHl2pQleQPQzWZRZstzlw2w==",
                            PermissionLevel = 1,
                            Role = "Mitarbeiter",
                            Username = "lena.brunner",
                            VacationDays = 22.0,
                            Workload = 80
                        },
                        new
                        {
                            Id = new Guid("144eda86-a7a2-419d-a37d-e16726e3828c"),
                            IsActive = false,
                            MustChangePassword = true,
                            Name = "Tiago de Sousa Sá",
                            PasswordHash = "AQAAAAIAAYagAAAAEB9r8iV+OfZIu2V5H1x/Hh3SM3oPW8VHpRdMSxKV+bTtHl2pQleQPQzWZRZstzlw2w==",
                            PermissionLevel = 1,
                            Role = "Mitarbeiter",
                            Username = "tiago.desousa",
                            VacationDays = 16.5,
                            Workload = 60
                        });
                });

            modelBuilder.Entity("FullstackRessourcix.AbsenceRequest", b =>
                {
                    b.HasOne("FullstackRessourcix.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
