// <auto-generated />
using System;
using FullstackRessourcix;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FullstackRessourcix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FullstackRessourcix.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Reference")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("audit_log_entries", (string)null);
                });

            modelBuilder.Entity("FullstackRessourcix.Employee", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("mustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("permissionLevel")
                        .HasColumnType("integer");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("vacationDays")
                        .HasColumnType("double precision");

                    b.Property<int>("workload")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            id = new Guid("4c3469de-428f-437e-b752-46f56714f063"),
                            isActive = true,
                            mustChangePassword = true,
                            name = "Morris Meier",
                            passwordHash = "AQAAAAIAAYagAAAAEB9r8iV+OfZIu2V5H1x/Hh3SM3oPW8VHpRdMSxKV+bTtHl2pQleQPQzWZRZstzlw2w==",
                            permissionLevel = 1,
                            role = "Mitarbeiter",
                            username = "morris.meier",
                            vacationDays = 25.0,
                            workload = 100
                        },
                        new
                        {
                            id = new Guid("86df2463-1bcd-42de-bb97-2cf112caeabf"),
                            isActive = true,
                            mustChangePassword = true,
                            name = "Pedro Santos",
                            passwordHash = "AQAAAAIAAYagAAAAEB9r8iV+OfZIu2V5H1x/Hh3SM3oPW8VHpRdMSxKV+bTtHl2pQleQPQzWZRZstzlw2w==",
                            permissionLevel = 5,
                            role = "Planer/Leitung",
                            username = "pedro.santos",
                            vacationDays = 25.0,
                            workload = 100
                        },
                        new
                        {
                            id = new Guid("77f37330-cb2b-4a5b-9f6a-6c2d19fde288"),
                            isActive = true,
                            mustChangePassword = true,
                            name = "Lena Brunner",
                            passwordHash = "AQAAAAIAAYagAAAAEB9r8iV+OfZIu2V5H1x/Hh3SM3oPW8VHpRdMSxKV+bTtHl2pQleQPQzWZRZstzlw2w==",
                            permissionLevel = 1,
                            role = "Mitarbeiter",
                            username = "lena.brunner",
                            vacationDays = 22.0,
                            workload = 80
                        },
                        new
                        {
                            id = new Guid("144eda86-a7a2-419d-a37d-e16726e3828c"),
                            isActive = false,
                            mustChangePassword = true,
                            name = "Tiago de Sousa Sá",
                            passwordHash = "AQAAAAIAAYagAAAAEB9r8iV+OfZIu2V5H1x/Hh3SM3oPW8VHpRdMSxKV+bTtHl2pQleQPQzWZRZstzlw2w==",
                            permissionLevel = 1,
                            role = "Mitarbeiter",
                            username = "tiago.desousa",
                            vacationDays = 16.5,
                            workload = 60
                        });
                });

            modelBuilder.Entity("FullstackRessourcix.Request", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("days")
                        .HasColumnType("integer");

                    b.Property<Guid>("employeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("from")
                        .HasColumnType("date");

                    b.Property<bool>("overlap")
                        .HasColumnType("boolean");

                    b.Property<string>("remark")
                        .HasColumnType("text");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("submittedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("until")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.HasIndex("employeeId");

                    b.ToTable("requests", (string)null);

                    b.HasData(
                        new
                        {
                            id = new Guid("7e978e11-0a00-4e05-b61a-007763f529cd"),
                            days = 10,
                            employeeId = new Guid("4c3469de-428f-437e-b752-46f56714f063"),
                            from = new DateOnly(2026, 7, 13),
                            overlap = true,
                            status = 0,
                            submittedOn = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            type = 0,
                            until = new DateOnly(2026, 7, 24)
                        });
                });

            modelBuilder.Entity("FullstackRessourcix.Request", b =>
                {
                    b.HasOne("FullstackRessourcix.Employee", null)
                        .WithMany()
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
